// src/pages/MyPage.tsx
// v2.8.1: 금융감독원 전문가 강의영상 메뉴 복원 (더보기 탭)
// v2.8.0: PIN 잠금 설정 메뉴 추가 (앱 잠금 설정 / PIN 변경 / PIN 해제)
// v2.7.0: 설정 화면 구현 - 알림, 화면, 보안, 데이터관리, 앱정보 (localStorage 연동)
// v2.6.5: 집 일러스트 부자지수 연동 수정 - financialResult.wealthIndex 우선, localStorage fallback
// v2.6.4: 프로필 영역 실데이터 연동 - 집 일러스트(부자지수 5단계) + DESIRE 진행바(금융집짓기 1단계 STEP5 결과)
// v2.6.3: 프로필 영역 일러스트 집 + DESIRE 6단계 진행바 복원
// v2.6.2: 전자책 모달 복원
// v2.6.1: 온라인강좌 107강 모달 UI 복원 (v2.2 스타일)
// - v2.2: 온라인강좌 페이지 연결
// - v2.3: 공유 URL, DESIRE 로드맵 (실제 financialHouseData 연동)
// - v2.4: 멤버십 플랜 (일반인/FP 탭, 월간/연간 선택, 카드결제 UI)
// - v2.5: mailto encodeURIComponent 수정, 전체 통합
// - v2.6: DESIRE 로드맵 → 원본 기획대로 재구현
// - v2.6.1: 온라인강좌 107강 모달 → v2.2 스타일 복원
//         (cyan/teal 그라데이션 소개 카드 + 가격 버튼 3개)

import { useState, useEffect, useRef } from 'react';
// ★★★ v2.8.0 추가: PIN 설정 화면 ★★★
import PinSetupScreen from '../components/PinSetupScreen';

// ─── 이미지 URL 상수 ───
const LOGO_URL = "https://firebasestorage.googleapis.com/v0/b/moneya-72fe6.firebasestorage.app/o/AI%EB%A8%B8%EB%8B%88%EC%95%BC%20%ED%99%95%EC%A0%95%EC%9D%B4%EB%AF%B8%EC%A7%80%EC%95%88.png?alt=media&token=c250863d-7cda-424a-800d-884b20e30b1a";
const PROFILE_IMAGE_URL = 'https://firebasestorage.googleapis.com/v0/b/moneya-72fe6.firebasestorage.app/o/%EC%98%A4%EC%83%81%EC%97%B4%20%EC%82%AC%EC%A7%84.png?alt=media&token=63eaf15e-9d0b-4d72-8fbb-ee03d6ecc8e5';
const EBOOK_COVER_URL = 'https://firebasestorage.googleapis.com/v0/b/moneya-72fe6.firebasestorage.app/o/financial-house-exterior.png.png?alt=media&token=e1651823-af8e-4ed3-9b3d-557a1bf0eb10';
const SHARE_URL = 'https://moneya-frontend.vercel.app';

// ─── 타입 정의 ───
interface FinancialResult { name: string; age: number; income: number; assets: number; debt: number; wealthIndex: number; level: number; houseName: string; houseImage: string; message: string; }
interface MembershipPlanItem { tier: string; price: number; priceDisplay: string; annual: number; annualDisplay: string; annualMonthly: string; badge: string; gradient: string; benefits: string[]; highlight: boolean; current: boolean; }

// ─── DESIRE 6단계 정의 ───
const DESIRE_STAGES = [
  { stage: 1, letter: 'D', name: 'Debt Free', title: '신용대출 상환', house: '🏚️', houseName: '초가집', color: '#dc2626', bgFrom: '#fee2e2', bgTo: '#fecaca', certGuide: '신용대출 상환 완료 인증샷을 첨부하세요', dataSource: '금융집짓기 > 부채설계 > 신용대출' },
  { stage: 2, letter: 'E', name: 'Emergency Fund', title: '비상예비자금 확보', house: '🏡', houseName: '나무집', color: '#ea580c', bgFrom: '#ffedd5', bgTo: '#fed7aa', certGuide: '비상예비자금 마련 금액을 인증하세요', dataSource: '금융집짓기 > 투자설계 > 비상예비자금' },
  { stage: 3, letter: 'S', name: 'Savings', title: '저축·연금 자동화', house: '🏠', houseName: '벽돌집', color: '#ca8a04', bgFrom: '#fef9c3', bgTo: '#fef08a', certGuide: '저축/투자 현황 인증샷을 첨부하세요', dataSource: '금융집짓기 > 예산설계 > 저축/연금' },
  { stage: 4, letter: 'I', name: 'Investment', title: '금융자산 10억', house: '🏢', houseName: '콘크리트', color: '#2563eb', bgFrom: '#dbeafe', bgTo: '#bfdbfe', certGuide: '금융자산 10억원 달성 인증샷을 첨부하세요', dataSource: '금융집짓기 > 투자설계 > 금융자산' },
  { stage: 5, letter: 'R', name: 'Retirement', title: '담보대출 상환', house: '🏛️', houseName: '대리석', color: '#7c3aed', bgFrom: '#ede9fe', bgTo: '#ddd6fe', certGuide: '담보대출 상환 완료 인증샷을 첨부하세요', dataSource: '금융집짓기 > 부채설계 > 담보대출' },
  { stage: 6, letter: 'E', name: 'Enjoy & Estate', title: '🎁 선물함', house: '🏰', houseName: '고급주택', color: '#059669', bgFrom: '#d1fae5', bgTo: '#a7f3d0', certGuide: '', dataSource: '' },
];

interface LoanItem { id: number; name: string; amount: number; rate: number; }
interface DesireStageDetail { summary: string; creditLoans?: LoanItem[]; mortgageLoans?: LoanItem[]; emergencyFund?: { current: number; target: number; secured: boolean }; savings?: { monthlySaving: number; monthlyPension: number; irregularIncome: number; budgetTotal: number }; investment?: { financialAssets: number; target: number }; }

const FAQ_DATA = [
  { q: '금융집짓기®란 무엇인가요?', a: '오원트금융연구소에서 개발한 재무설계 방법론으로, 집을 짓듯이 체계적으로 금융 계획을 세우는 프로그램입니다.' },
  { q: '유료 구독 요금은 얼마인가요?', a: '일반인용: 베이직 12,900원, 스탠다드 29,000원, 프리미엄 59,000원 / FP용: 베이직 33,000원, 스탠다드 59,000원, 프리미엄 99,000원입니다.' },
  { q: 'AI 지출 상담은 어떻게 이용하나요?', a: 'AI지출 탭에서 음성 또는 텍스트로 지출에 대해 상담받으실 수 있습니다.' },
  { q: '재무설계 리포트는 어디서 볼 수 있나요?', a: '더보기 > 월간 리포트에서 확인하실 수 있습니다.' },
  { q: '전문가 상담은 어떻게 신청하나요?', a: '더보기 > 오상열 대표 강의·상담 신청에서 원하시는 상담 유형을 선택하여 신청하실 수 있습니다.' },
  { q: '개인정보는 안전하게 보호되나요?', a: '네, 모든 개인정보는 암호화되어 안전하게 보관됩니다.' },
  { q: '회원 탈퇴는 어떻게 하나요?', a: '더보기 > 회원탈퇴에서 탈퇴 신청하실 수 있습니다. 탈퇴 시 모든 데이터가 삭제됩니다.' },
];

const MEMBERSHIP_PLANS: Record<string, MembershipPlanItem[]> = {
  general: [
    { tier: 'FREE', price: 0, priceDisplay: '무료', annual: 0, annualDisplay: '0', annualMonthly: '0', badge: '🆓', gradient: 'from-gray-400 to-gray-500', benefits: ['AI머니야 전체 기능 체험', '7일간 프리미엄급 이용'], highlight: false, current: true },
    { tier: 'BASIC', price: 12900, priceDisplay: '12,900', annual: 129000, annualDisplay: '129,000', annualMonthly: '10,750', badge: '🥉', gradient: 'from-blue-500 to-blue-600', benefits: ['AI머니야 전체 기능', '금융집짓기® 전자책 제공', '(12,900원 상당)'], highlight: false, current: false },
    { tier: 'STANDARD', price: 29000, priceDisplay: '29,000', annual: 290000, annualDisplay: '290,000', annualMonthly: '24,167', badge: '🥈', gradient: 'from-purple-500 to-indigo-600', benefits: ['BASIC 전체 포함', '온라인강좌 107강 무제한', '전자책 + 강좌 올인원'], highlight: true, current: false },
    { tier: 'PREMIUM', price: 59000, priceDisplay: '59,000', annual: 590000, annualDisplay: '590,000', annualMonthly: '49,167', badge: '🥇', gradient: 'from-amber-500 to-amber-600', benefits: ['STANDARD 전체 포함', '월례 ZOOM 세미나 참석', '오상열 CFP 직접 강의'], highlight: false, current: false },
  ],
  fp: [
    { tier: 'FREE', price: 0, priceDisplay: '무료', annual: 0, annualDisplay: '0', annualMonthly: '0', badge: '🆓', gradient: 'from-gray-400 to-gray-500', benefits: ['AI머니야 전체 기능 체험', '7일간 프리미엄급 이용'], highlight: false, current: true },
    { tier: 'BASIC', price: 33000, priceDisplay: '33,000', annual: 330000, annualDisplay: '330,000', annualMonthly: '27,500', badge: '🥉', gradient: 'from-blue-500 to-blue-600', benefits: ['일반인 STANDARD 전체 포함', '고객 100명 등록 관리', '전자책 + 온라인강좌 107강'], highlight: false, current: false },
    { tier: 'STANDARD', price: 59000, priceDisplay: '59,000', annual: 590000, annualDisplay: '590,000', annualMonthly: '49,167', badge: '🥈', gradient: 'from-purple-500 to-indigo-600', benefits: ['일반인 PREMIUM 전체 포함', '고객 500명 등록 관리', '월례 ZOOM 세미나 포함'], highlight: true, current: false },
    { tier: 'PREMIUM', price: 99000, priceDisplay: '99,000', annual: 990000, annualDisplay: '990,000', annualMonthly: '82,500', badge: '🥇', gradient: 'from-amber-500 to-amber-600', benefits: ['일반인 PREMIUM 전체 포함', '고객 무제한 등록 관리', '월례 ZOOM 세미나 포함'], highlight: false, current: false },
  ],
};

const formatCardNumber = (v: string): string => { const nums = v.replace(/\D/g, '').slice(0, 16); return nums.replace(/(\d{4})(?=\d)/g, '$1-'); };
const formatExpiry = (v: string): string => { const nums = v.replace(/\D/g, '').slice(0, 4); if (nums.length > 2) return nums.slice(0, 2) + '/' + nums.slice(2); return nums; };

interface MyPageProps { userName: string; userEmail: string; userPhoto: string | null; financialResult: FinancialResult | null; onNavigate: (page: 'subscription' | 'consulting' | 'monthly-report' | 'online-course' | 'podcast') => void; onLogout: () => void; onReset: () => void; userId?: string; }

export default function MyPage({ userName, userEmail, userPhoto: _userPhoto, financialResult: _financialResult, onNavigate, onLogout, onReset, userId }: MyPageProps) {
  const [showResetConfirm, setShowResetConfirm] = useState(false);
  const [showProfileEdit, setShowProfileEdit] = useState(false);
  const [showSettings, setShowSettings] = useState(false);
  const [settingNotification, setSettingNotification] = useState(() => localStorage.getItem('moneya_setting_notification') !== 'false');
  const [settingDailyReminder, setSettingDailyReminder] = useState(() => localStorage.getItem('moneya_setting_dailyReminder') !== 'false');
  const [settingSound, setSettingSound] = useState(() => localStorage.getItem('moneya_setting_sound') !== 'false');
  const [settingBioAuth, setSettingBioAuth] = useState(() => localStorage.getItem('moneya_setting_bioAuth') === 'true');
  const [settingAmountUnit, setSettingAmountUnit] = useState<'만원' | '원'>(() => (localStorage.getItem('moneya_setting_amountUnit') as '만원' | '원') || '만원');
  const [showCacheClearDone, setShowCacheClearDone] = useState(false);
  const [showFAQ, setShowFAQ] = useState(false);
  const [showTerms, setShowTerms] = useState(false);
  const [showPrivacy, setShowPrivacy] = useState(false);
  const [showWithdraw, setShowWithdraw] = useState(false);
  const [showDesireRoadmap, setShowDesireRoadmap] = useState(false);
  const [showOnlineCourse, setShowOnlineCourse] = useState(false);
  const [showEbook, setShowEbook] = useState(false);
  const [showShare, setShowShare] = useState(false);
  const [showPinSetup, setShowPinSetup] = useState(false);
  const [pinMode, setPinMode] = useState<'setup' | 'change' | 'disable'>('setup');
  const pinEnabled = userId ? localStorage.getItem(`moneya_pin_enabled_${userId}`) === 'true' : false;
  const [pinEnabledState, setPinEnabledState] = useState(pinEnabled);
  const [showExpertConsult, setShowExpertConsult] = useState(false);
  const [consultView, setConsultView] = useState<'list' | 'schedule' | 'confirm'>('list');
  const [consultSelectedType, setConsultSelectedType] = useState<any>(null);
  const [consultSelectedMonth, setConsultSelectedMonth] = useState<number | null>(null);
  const [consultBookings, setConsultBookings] = useState<any[]>([]);
  const [consultToast, setConsultToast] = useState<string | null>(null);
  const [showMembership, setShowMembership] = useState(false);
  const [membershipTab, setMembershipTab] = useState<'general' | 'fp'>('general');
  const [membershipStep, setMembershipStep] = useState<'list' | 'cycle' | 'payment' | 'done'>('list');
  const [selectedMembershipPlan, setSelectedMembershipPlan] = useState<MembershipPlanItem | null>(null);
  const [billingCycle, setBillingCycle] = useState<'monthly' | 'annual' | null>(null);
  const [cardNumber, setCardNumber] = useState('');
  const [cardExpiry, setCardExpiry] = useState('');
  const [cardCvc, setCardCvc] = useState('');
  const [cardHolder, setCardHolder] = useState('');
  const [isPayProcessing, setIsPayProcessing] = useState(false);
  const [editName, setEditName] = useState(userName);
  const [openFaqIndex, setOpenFaqIndex] = useState<number | null>(null);
  const [desireExpandedStage, setDesireExpandedStage] = useState<number | null>(null);
  const [desireStageDetails, setDesireStageDetails] = useState<Record<number, DesireStageDetail>>({});
  const [desireCompleted, setDesireCompleted] = useState<Record<number, boolean>>({});
  const [desireLoanChecks, setDesireLoanChecks] = useState<Record<string, boolean>>({});
  const [desirePhotos, setDesirePhotos] = useState<Record<number, string>>({});
  const [showCelebration, setShowCelebration] = useState(false);
  const [giftOpened, setGiftOpened] = useState(false);
  const photoInputRef = useRef<HTMLInputElement>(null);
  const [activePhotoStage, setActivePhotoStage] = useState<number | null>(null);
  const [showStoryForm, setShowStoryForm] = useState(false);
  const [storyNickname, setStoryNickname] = useState('');
  const [storyDesireStage, setStoryDesireStage] = useState('D');
  const [storyContent, setStoryContent] = useState('');
  const [storyContact, setStoryContact] = useState('');
  const [storyAgree, setStoryAgree] = useState(true);
  const [storySubmitted, setStorySubmitted] = useState(false);

  useEffect(() => {
    const details: Record<number, DesireStageDetail> = {};
    try {
      const raw = localStorage.getItem('financialHouseData');
      if (!raw) { for (let i = 1; i <= 6; i++) details[i] = { summary: '금융집짓기에서 데이터를 먼저 입력해주세요' }; setDesireStageDetails(details); return; }
      const data = JSON.parse(raw);
      const creditLoans: LoanItem[] = (data?.debtDesign?.creditLoans || []).map((l: any, idx: number) => ({ id: idx + 1, name: l.name || l.loanName || `신용대출 ${idx + 1}`, amount: Number(l.amount || l.loanAmount || 0), rate: Number(l.rate || l.interestRate || 0) })).sort((a: LoanItem, b: LoanItem) => b.rate - a.rate);
      const creditTotal = creditLoans.reduce((s, l) => s + l.amount, 0);
      details[1] = { summary: creditTotal > 0 ? `신용대출 ${creditLoans.length}건 · ${(creditTotal / 10000).toLocaleString()}만원` : '신용대출 없음 ✅', creditLoans };
      const ef = data?.investDesign?.emergencyFund || 0; const efTarget = data?.investDesign?.emergencyFundTarget || (data?.budgetDesign?.monthlyExpense || 0) * 6; const efSecured = ef >= efTarget && efTarget > 0;
      details[2] = { summary: ef > 0 ? `비상예비자금 ${(ef / 10000).toLocaleString()}만원 확보` : '비상예비자금 미설정', emergencyFund: { current: ef, target: efTarget, secured: efSecured } };
      const monthlySaving = data?.budgetDesign?.monthlySavings || data?.budgetDesign?.monthlySaving || 0; const monthlyPension = data?.budgetDesign?.monthlyPension || 0; const irregularIncome = data?.budgetDesign?.irregularIncome || 0; const budgetTotal = data?.budgetDesign?.totalBudget || data?.budgetDesign?.monthlyIncome || 0;
      details[3] = { summary: (monthlySaving + monthlyPension) > 0 ? `월 저축+연금 ${((monthlySaving + monthlyPension) / 10000).toLocaleString()}만원` : '저축/연금 미설정', savings: { monthlySaving, monthlyPension, irregularIncome, budgetTotal } };
      const fa = data?.investDesign?.financialAssets || 0; const target10 = 1000000000;
      details[4] = { summary: fa > 0 ? `금융자산 ${(fa / 100000000).toFixed(1)}억원` : '금융자산 미입력', investment: { financialAssets: fa, target: target10 } };
      const mortgageLoans: LoanItem[] = (data?.debtDesign?.mortgageLoans || []).map((l: any, idx: number) => ({ id: idx + 1, name: l.name || l.loanName || `담보대출 ${idx + 1}`, amount: Number(l.amount || l.loanAmount || 0), rate: Number(l.rate || l.interestRate || 0) })).sort((a: LoanItem, b: LoanItem) => b.rate - a.rate);
      const mortgageTotal = mortgageLoans.reduce((s, l) => s + l.amount, 0);
      details[5] = { summary: mortgageTotal > 0 ? `담보대출 ${mortgageLoans.length}건 · ${(mortgageTotal / 10000).toLocaleString()}만원` : '담보대출 없음 ✅', mortgageLoans };
      details[6] = { summary: '1~5단계를 모두 완료하면 열립니다' };
      setDesireStageDetails(details);
    } catch (e) { console.error('DESIRE 데이터 로드 실패:', e); }
    try { const sc = localStorage.getItem('desireCompleted'); if (sc) setDesireCompleted(JSON.parse(sc)); const lc = localStorage.getItem('desireLoanChecks'); if (lc) setDesireLoanChecks(JSON.parse(lc)); const ph = localStorage.getItem('desirePhotos'); if (ph) setDesirePhotos(JSON.parse(ph)); const go = localStorage.getItem('desireGiftOpened'); if (go) setGiftOpened(true); } catch { /* ignore */ }
  }, [showDesireRoadmap]);

  const handleDesireComplete = (stage: number) => { const next = { ...desireCompleted, [stage]: !desireCompleted[stage] }; setDesireCompleted(next); localStorage.setItem('desireCompleted', JSON.stringify(next)); };
  const handleLoanCheck = (key: string) => { const next = { ...desireLoanChecks, [key]: !desireLoanChecks[key] }; setDesireLoanChecks(next); localStorage.setItem('desireLoanChecks', JSON.stringify(next)); };
  const handlePhotoAttach = (stage: number) => { setActivePhotoStage(stage); photoInputRef.current?.click(); };
  const handlePhotoChange = (e: React.ChangeEvent<HTMLInputElement>) => { const file = e.target.files?.[0]; if (!file || activePhotoStage === null) return; const reader = new FileReader(); reader.onload = (ev) => { const url = ev.target?.result as string; const next = { ...desirePhotos, [activePhotoStage]: url }; setDesirePhotos(next); localStorage.setItem('desirePhotos', JSON.stringify(next)); }; reader.readAsDataURL(file); e.target.value = ''; };
  const handleOpenGift = () => { setGiftOpened(true); setShowCelebration(true); localStorage.setItem('desireGiftOpened', 'true'); };
  const isStageComplete = (stage: number): boolean => { if (stage === 6) return [1, 2, 3, 4, 5].every(s => isStageComplete(s)); return !!desireCompleted[stage]; };
  const DESIRE_CHIP_OPTIONS = [ { key: 'D', label: '💳 D-빚갚기' }, { key: 'E1', label: '🛡️ E-비상금' }, { key: 'S', label: '💰 S-저축' }, { key: 'I', label: '📈 I-투자' }, { key: 'R', label: '🏠 R-부동산' }, { key: 'E2', label: '🏖️ E-은퇴' } ];
  const handleStorySubmit = () => { if (!storyNickname.trim() || storyContent.trim().length < 50 || !storyAgree) { alert(!storyNickname.trim() ? '닉네임을 입력해주세요.' : storyContent.trim().length < 50 ? '사연을 50자 이상 작성해주세요.' : '개인정보 동의가 필요합니다.'); return; } const mailto = `mailto:ggorilla11@gmail.com?subject=${encodeURIComponent(`[AI머니야] DESIRE 사례 신청 - ${storyNickname}`)}&body=${encodeURIComponent(`닉네임: ${storyNickname}\nDESIRE 단계: ${storyDesireStage}\n\n사연:\n${storyContent}\n\n연락처: ${storyContact || '미입력'}`)}`; window.location.href = mailto; setStorySubmitted(true); };
  const resetStoryForm = () => { setStoryNickname(''); setStoryDesireStage('D'); setStoryContent(''); setStoryContact(''); setStoryAgree(true); setStorySubmitted(false); setShowStoryForm(false); };
  const handleInquiry = () => { const to = 'ggorilla11@gmail.com'; const subject = encodeURIComponent('[AI머니야] 1:1 문의'); const body = encodeURIComponent('문의 내용을 작성해주세요.'); window.location.href = `mailto:${to}?subject=${subject}&body=${body}`; };
  const handleSelectPlan = (plan: MembershipPlanItem) => { if (plan.current) return; setSelectedMembershipPlan(plan); setBillingCycle(null); setMembershipStep('cycle'); };
  const handleSelectCycle = (cycle: 'monthly' | 'annual') => { setBillingCycle(cycle); setMembershipStep('payment'); setCardNumber(''); setCardExpiry(''); setCardCvc(''); setCardHolder(''); };
  const handlePay = () => { if (!cardNumber || !cardExpiry || !cardCvc || !cardHolder) { alert('모든 항목을 입력해주세요.'); return; } setIsPayProcessing(true); setTimeout(() => { setIsPayProcessing(false); setMembershipStep('done'); }, 2000); };
  const closeMembership = () => { setShowMembership(false); setMembershipStep('list'); setSelectedMembershipPlan(null); setBillingCycle(null); };
  const shareText = `💰 AI머니야 - AI 기반 재무관리 앱\n금융집짓기® 방법론으로 체계적인 재무설계를 시작하세요!\n\n👉 ${SHARE_URL}`;
  const handleShare = async (method: string) => {
    if (method === 'copy') { try { await navigator.clipboard.writeText(SHARE_URL); alert('링크가 복사되었습니다!'); } catch { alert(SHARE_URL); } }
    else if (method === 'kakao') { window.open(`https://sharer.kakao.com/talk/friends/picker/link?url=${encodeURIComponent(SHARE_URL)}&text=${encodeURIComponent(shareText)}`, '_blank', 'width=500,height=600'); }
    else if (method === 'sms') { window.location.href = `sms:?body=${encodeURIComponent(shareText)}`; }
    else if (method === 'email') { const subject = '[추천] AI머니야 - AI 기반 재무관리 앱'; const body = `안녕하세요!\n\nAI머니야를 추천드립니다.\n금융집짓기® 방법론으로 체계적인 재무설계를 시작하세요!\n\n👉 ${SHARE_URL}\n\nQR코드로도 접속 가능합니다.`; window.location.href = `mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`; }
    else if (method === 'native') { if (navigator.share) { try { await navigator.share({ title: 'AI머니야 - AI 기반 재무관리 앱', text: '금융집짓기® 방법론으로 체계적인 재무설계를 시작하세요!', url: SHARE_URL }); } catch { /* cancel */ } } else { try { await navigator.clipboard.writeText(shareText); alert('링크가 복사되었습니다!'); } catch { alert(SHARE_URL); } } }
  };
  const handleResetClick = () => setShowResetConfirm(true);
  const handleResetConfirm = () => { setShowResetConfirm(false); onReset(); };
  const CONSULT_YEAR = 2026;
  const CONSULT_SCHEDULE: Record<string, { label: string; months: Record<number, number[]> }> = { expert: { label: '전문가 강의', months: { 3: [7,14,21,28], 4: [4,11,18,25], 5: [2,9,16,23], 6: [6,13,20,27], 7: [4,11,18,25], 8: [1,8,22,29], 9: [5,12,19,26], 10: [10,17,24,31], 11: [7,14,21,28], 12: [5,12,19,26] } }, general: { label: '일반인 강의', months: { 3: [9,16,23,30], 4: [6,13,20,27], 5: [4,11,18,25], 6: [8,15,22,29], 7: [6,13,20,27], 8: [3,10,24,31], 9: [7,14,21,28], 10: [12,19,26], 11: [9,16,23,30], 12: [7,14,21,28] } } };
  const PAYPLE_LINKS: Record<string, string> = { 'non-face': 'https://link.payple.kr/NzcxOjc2ODQ3NzYyNzY3MDU5', 'face': 'https://link.payple.kr/NzcxOjc2ODQ3NzU4NjYzMDE4', 'vip': 'https://link.payple.kr/NzcxOjc2OD', 'expert-lecture': 'https://link.payple.kr/NzcxOjc3MDA2MDc4OTM1OTgz', 'general-lecture': 'https://link.payple.kr/NzcxOjc2ODQ3NzcyMjc4MzY3' };
  const CONSULT_TYPES = [
    { id: 'general-lecture', icon: '📚', title: '일반인 강의', desc: '누구나 들을 수 있는 재무설계 기초 강의', detail: '비대면 · 월 4회 · 연간 일정표 제공', price: 550000, priceLabel: '55만원', sessions: 4, category: 'lecture' as const, scheduleType: 'general' },
    { id: 'expert-lecture', icon: '🎓', title: '전문가 강의', desc: '보험설계사·FP 대상 실전 재무설계 강의', detail: '대면+비대면 · 월 4회 · 1년 과정', price: 1100000, priceLabel: '110만원', priceSub: '1년 과정', sessions: 4, category: 'lecture' as const, scheduleType: 'expert' },
    { id: 'non-face', icon: '💰', title: '비대면 상담', desc: '화상으로 진행되는 1:1 맞춤 재무상담', detail: '2회 진행 · 일정 별도 협의', price: 330000, priceLabel: '33만원', sessions: 2, category: 'consultation' as const },
    { id: 'face', icon: '💵', title: '대면 상담', desc: '직접 만나서 진행하는 심층 재무상담', detail: '2회 진행 · 일정 별도 협의', price: 550000, priceLabel: '55만원', sessions: 2, category: 'consultation' as const },
    { id: 'vip', icon: '📈', title: '자산가 상담', desc: '금융자산 10억원 초과 고객 전용 VIP 상담', detail: '3회 진행 · 일정 별도 협의', price: 1100000, priceLabel: '110만원', sessions: 3, premium: true, category: 'consultation' as const },
  ];
  const getConsultDow = (y: number, m: number, d: number) => ['일','월','화','수','목','금','토'][new Date(y, m-1, d).getDay()];
  const isConsultMonthPast = (m: number) => { const now = new Date(); return new Date(CONSULT_YEAR, m-1, 28) < now; };
  const handleConsultSelectType = (type: any) => { setConsultSelectedType(type); setConsultSelectedMonth(null); setConsultView(type.category === 'lecture' ? 'schedule' : 'confirm'); };
  const handleConsultSelectMonth = (m: number) => { if (isConsultMonthPast(m)) return; setConsultSelectedMonth(consultSelectedMonth === m ? null : m); };
  const handleConsultGoBack = () => { if (consultView === 'confirm' && consultSelectedType?.category === 'lecture') { setConsultView('schedule'); return; } setConsultView('list'); setConsultSelectedType(null); setConsultSelectedMonth(null); };
  const handleConsultPayment = () => { const typeId = consultSelectedType?.id; if (!typeId) return; const payUrl = PAYPLE_LINKS[typeId]; const sd = consultSelectedType?.scheduleType ? CONSULT_SCHEDULE[consultSelectedType.scheduleType] : null; const dates = sd && consultSelectedMonth ? sd.months[consultSelectedMonth] : []; setConsultBookings(prev => [...prev, { id: Date.now(), type: consultSelectedType, month: consultSelectedMonth, dates }]); setConsultToast(consultSelectedMonth ? `${CONSULT_YEAR}년 ${consultSelectedMonth}월 (${dates.length}회) 결제 페이지로 이동합니다` : `${consultSelectedType.title} 결제 페이지로 이동합니다`); setTimeout(() => setConsultToast(null), 2800); if (payUrl) window.open(payUrl, '_blank'); setConsultView('list'); setConsultSelectedType(null); setConsultSelectedMonth(null); };
  const openExpertConsultModal = () => { setShowExpertConsult(true); setConsultView('list'); setConsultSelectedType(null); setConsultSelectedMonth(null); };
  const closeExpertConsultModal = () => { setShowExpertConsult(false); setConsultView('list'); setConsultSelectedType(null); setConsultSelectedMonth(null); };
  const consultScheduleData = consultSelectedType?.scheduleType ? CONSULT_SCHEDULE[consultSelectedType.scheduleType] : null;
  const consultAvailableMonths = consultScheduleData ? Object.keys(consultScheduleData.months).map(Number) : [];
  const displayName = userName.split('(')[0].trim();
  const financialHouseData = (() => { try { const raw = localStorage.getItem('financialHouseData'); if (!raw) return null; return JSON.parse(raw); } catch { return null; } })();
  const wealthIndexToLevel = (wi: number): number => { if (wi <= 0) return 1; if (wi <= 50) return 2; if (wi <= 100) return 3; if (wi <= 200) return 4; return 5; };
  const { houseLevel, actualWealthIndex } = (() => {
    if (_financialResult && _financialResult.wealthIndex > 0) { return { houseLevel: _financialResult.level || wealthIndexToLevel(_financialResult.wealthIndex), actualWealthIndex: _financialResult.wealthIndex }; }
    if (financialHouseData) { const p = financialHouseData.personalInfo; const inc = financialHouseData.income; const ageVal = p?.age || 0; const monthlyIncome = (inc?.myIncome || 0) + (inc?.spouseIncome || 0) + (inc?.otherIncome || 0); const totalAsset = financialHouseData.totalAsset || 0; const totalDebt = financialHouseData.debts?.totalDebt || 0; const netAsset = totalAsset - totalDebt; if (ageVal <= 0 || monthlyIncome <= 0) { return { houseLevel: 1 as number, actualWealthIndex: 0 }; } const wi = (netAsset * 10) / (ageVal * monthlyIncome * 12) * 100; return { houseLevel: wealthIndexToLevel(wi), actualWealthIndex: Math.round(wi) }; }
    return { houseLevel: null as number | null, actualWealthIndex: 0 };
  })();
  const HOUSE_LEVELS = [ { level: 1, house: '🏚️', houseName: '초가집', weather: '⛈️', bgColor: 'from-red-100 to-red-50', label: '미흡' }, { level: 2, house: '🏠', houseName: '나무집', weather: '☁️', bgColor: 'from-orange-100 to-orange-50', label: '보통' }, { level: 3, house: '🏡', houseName: '벽돌집', weather: '⛅', bgColor: 'from-yellow-100 to-yellow-50', label: '양호' }, { level: 4, house: '🏛️', houseName: '콘크리트', weather: '☀️', bgColor: 'from-blue-100 to-blue-50', label: '우수' }, { level: 5, house: '🏰', houseName: '고급주택', weather: '🌈', bgColor: 'from-emerald-100 to-emerald-50', label: '훌륭' } ];
  const currentHouseInfo = houseLevel ? HOUSE_LEVELS[houseLevel - 1] : null;
  const desireStage: number | null = (() => { if (!financialHouseData) return null; if (financialHouseData.desireStage?.stage) return financialHouseData.desireStage.stage; return 1; })();
  const desireTextColor = desireStage ? ['text-red-600', 'text-orange-600', 'text-yellow-600', 'text-blue-600', 'text-purple-600', 'text-emerald-600'][desireStage - 1] : 'text-gray-400';

  return (
    <div className="min-h-screen bg-gray-50 pb-24">
      {/* ─── 프로필 섹션 ─── */}
      <div className="bg-white p-5 border-b border-gray-200">
        <div className="flex gap-4">
          <div className="flex-1 flex flex-col justify-between">
            <div className="flex items-center gap-3 mb-3"><img src={LOGO_URL} alt="AI머니야 로고" className="w-14 h-14" /><div><p className="font-extrabold text-lg text-gray-900">{displayName}님</p><p className="text-sm text-gray-500">{userEmail}</p></div></div>
            <div className="inline-flex items-center gap-2 px-4 py-2.5 bg-gradient-to-r from-purple-50 to-indigo-50 border border-purple-200 rounded-xl self-start"><span className="text-base">👑</span><span className="text-sm font-bold text-purple-600">프리미엄급 이용 중</span><span className="text-xs text-gray-500 ml-1">무료체험</span></div>
          </div>
          <div className="flex flex-col items-center justify-center w-32">
            {currentHouseInfo ? (<><div className={`w-24 h-24 rounded-2xl bg-gradient-to-br ${currentHouseInfo.bgColor} flex flex-col items-center justify-center shadow-md border border-gray-100`}><span className="text-base mb-0.5">{currentHouseInfo.weather}</span><span className="text-4xl">{currentHouseInfo.house}</span><span className="text-[10px] text-gray-600 font-semibold mt-0.5">{currentHouseInfo.houseName}</span></div><div className="w-full mt-2">{desireStage ? (<><div className="flex items-center justify-center gap-1 mb-1.5"><span className={`text-xs font-bold ${desireTextColor}`}>DESIRE</span><span className="text-xs text-gray-600 font-semibold">{desireStage}단계</span></div><div className="flex gap-1">{[1,2,3,4,5,6].map((step) => (<div key={step} className={`h-2 flex-1 rounded-full ${step <= desireStage ? step <= 2 ? 'bg-red-400' : step <= 4 ? 'bg-yellow-400' : 'bg-emerald-400' : 'bg-gray-200'}`} />))}</div><div className="flex justify-between mt-1">{[1,2,3,4,5,6].map((step) => (<span key={step} className={`text-[9px] ${step === desireStage ? 'font-bold text-gray-800' : 'text-gray-400'}`}>{step}</span>))}</div></>) : (<div className="text-center mt-1"><span className="text-[9px] text-gray-400">부자지수 {actualWealthIndex.toLocaleString()}%</span></div>)}</div></>) : (<div className="w-24 h-24 rounded-2xl bg-gray-100 flex flex-col items-center justify-center border border-gray-200"><span className="text-3xl mb-1">🏠</span><span className="text-[9px] text-gray-400 text-center">재무설계를<br/>시작하세요</span></div>)}
          </div>
        </div>
      </div>
      {/* ─── 오상열 CFP 배너 ─── */}
      <div className="mx-4 mt-3"><div className="bg-gradient-to-r from-amber-50 to-yellow-50 border border-amber-200 rounded-xl p-4 flex items-center gap-3"><img src={PROFILE_IMAGE_URL} alt="오상열 CFP" className="w-14 h-14 rounded-full object-cover border-2 border-amber-300" /><div className="flex-1"><p className="text-sm font-bold text-amber-800">오상열 CFP</p><p className="text-xs text-amber-600">20년 경력 재무설계 전문가</p><p className="text-xs text-amber-500 mt-0.5">오원트금융연구소 대표</p></div><button onClick={openExpertConsultModal} className="px-3 py-2 bg-amber-500 text-white text-xs font-bold rounded-lg hover:bg-amber-600">강의상담신청</button></div></div>
      {/* ─── 메뉴 리스트 (v2.8.1: 금융감독원 강의영상 복원) ─── */}
      <div className="mx-4 mt-3 bg-white rounded-xl shadow-sm overflow-hidden">
        <button onClick={() => setShowDesireRoadmap(true)} className="w-full flex items-center gap-3 px-4 py-3.5 border-b border-gray-100 hover:bg-gray-50 text-left"><span className="w-8 h-8 bg-gradient-to-br from-emerald-400 to-teal-500 rounded-lg flex items-center justify-center text-white text-sm">🗺️</span><span className="flex-1 text-sm font-semibold text-gray-700">DESIRE 로드맵</span><span className="text-xs text-emerald-500 font-bold">NEW</span><span className="text-gray-400 text-sm">›</span></button>
        <button onClick={() => setShowMembership(true)} className="w-full flex items-center gap-3 px-4 py-3.5 border-b border-gray-100 hover:bg-gray-50 text-left"><span className="w-8 h-8 bg-gradient-to-br from-purple-400 to-indigo-500 rounded-lg flex items-center justify-center text-white text-sm">👑</span><span className="flex-1 text-sm font-semibold text-gray-700">멤버십 플랜</span><span className="text-gray-400 text-sm">›</span></button>
        <button onClick={() => setShowOnlineCourse(true)} className="w-full flex items-center gap-3 px-4 py-3.5 border-b border-gray-100 hover:bg-gray-50 text-left"><span className="w-8 h-8 bg-gradient-to-br from-blue-400 to-blue-500 rounded-lg flex items-center justify-center text-white text-sm">🎓</span><span className="flex-1 text-sm font-semibold text-gray-700">온라인강좌 107강 신청</span><span className="text-gray-400 text-sm">›</span></button>
        <button onClick={() => onNavigate('podcast')} className="w-full flex items-center gap-3 px-4 py-3.5 border-b border-gray-100 hover:bg-gray-50 text-left"><span className="w-8 h-8 bg-gradient-to-br from-slate-600 to-slate-800 rounded-lg flex items-center justify-center text-white text-sm">🎙️</span><span className="flex-1 text-sm font-semibold text-gray-700">팟캐스트 코너</span><span className="text-xs text-emerald-500 font-bold">NEW</span><span className="text-gray-400 text-sm">›</span></button>
        <button onClick={() => setShowEbook(true)} className="w-full flex items-center gap-3 px-4 py-3.5 border-b border-gray-100 hover:bg-gray-50 text-left"><span className="w-8 h-8 bg-gradient-to-br from-orange-400 to-orange-500 rounded-lg flex items-center justify-center text-white text-sm">📖</span><span className="flex-1 text-sm font-semibold text-gray-700">금융집짓기® 전자책</span><span className="text-gray-400 text-sm">›</span></button>
        <button onClick={openExpertConsultModal} className="w-full flex items-center gap-3 px-4 py-3.5 border-b border-gray-100 hover:bg-gray-50 text-left"><span className="w-8 h-8 bg-gradient-to-br from-pink-400 to-rose-500 rounded-lg flex items-center justify-center text-white text-sm">👨‍🏫</span><span className="flex-1 text-sm font-semibold text-gray-700">오상열 대표 강의·상담 신청</span><span className="text-gray-400 text-sm">›</span></button>
        {/* ★★★ v2.8.1 복원: 금융감독원 전문가 강의영상 ★★★ */}
        <button onClick={() => window.open('https://www.fss.or.kr/fss/ntcn/fncsusvPrMng/view.do?dataSlno=78&dataTrgtCode=02&menuNo=200266', '_blank')} className="w-full flex items-center gap-3 px-4 py-3.5 border-b border-gray-100 hover:bg-gray-50 text-left"><span className="w-8 h-8 bg-gradient-to-br from-red-400 to-pink-500 rounded-lg flex items-center justify-center text-white text-sm">🎬</span><span className="flex-1 text-sm font-semibold text-gray-700">금융감독원 전문가 강의영상</span><span className="text-gray-400 text-sm">›</span></button>
        <button onClick={() => onNavigate('monthly-report')} className="w-full flex items-center gap-3 px-4 py-3.5 border-b border-gray-100 hover:bg-gray-50 text-left"><span className="w-8 h-8 bg-gradient-to-br from-cyan-400 to-cyan-500 rounded-lg flex items-center justify-center text-white text-sm">📊</span><span className="flex-1 text-sm font-semibold text-gray-700">월간 리포트</span><span className="text-gray-400 text-sm">›</span></button>
        <button onClick={handleInquiry} className="w-full flex items-center gap-3 px-4 py-3.5 border-b border-gray-100 hover:bg-gray-50 text-left"><span className="w-8 h-8 bg-gradient-to-br from-green-400 to-green-500 rounded-lg flex items-center justify-center text-white text-sm">💬</span><span className="flex-1 text-sm font-semibold text-gray-700">1:1 문의하기</span><span className="text-gray-400 text-sm">›</span></button>
        <button onClick={() => setShowShare(true)} className="w-full flex items-center gap-3 px-4 py-3.5 hover:bg-gray-50 text-left"><span className="w-8 h-8 bg-gradient-to-br from-violet-400 to-violet-500 rounded-lg flex items-center justify-center text-white text-sm">🔗</span><span className="flex-1 text-sm font-semibold text-gray-700">친구에게 공유하기</span><span className="text-gray-400 text-sm">›</span></button>
      </div>
      {/* ─── 기타 메뉴 ─── */}
      <div className="mx-4 mt-3 mb-4">
        <div className="bg-white rounded-xl shadow-sm overflow-hidden">
          <button onClick={() => { if (!pinEnabledState) { setPinMode('setup'); setShowPinSetup(true); } }} className="w-full flex items-center gap-3 px-4 py-3 border-b border-gray-100 hover:bg-gray-50 text-left"><span className="text-gray-400">🔐</span><div className="flex-1"><span className="text-sm text-gray-600">앱 잠금 설정</span><p className="text-xs text-gray-400">PIN 번호로 앱을 보호합니다</p></div><span className={`text-xs font-bold px-2 py-0.5 rounded-full ${pinEnabledState ? 'bg-green-100 text-green-600' : 'bg-gray-100 text-gray-400'}`}>{pinEnabledState ? 'ON' : 'OFF'}</span></button>
          {pinEnabledState && (<><button onClick={() => { setPinMode('change'); setShowPinSetup(true); }} className="w-full flex items-center gap-3 px-4 py-2.5 pl-12 border-b border-gray-100 hover:bg-gray-50 text-left"><span className="text-sm text-gray-500">🔄 PIN 변경</span></button><button onClick={() => { setPinMode('disable'); setShowPinSetup(true); }} className="w-full flex items-center gap-3 px-4 py-2.5 pl-12 border-b border-gray-100 hover:bg-gray-50 text-left"><span className="text-sm text-red-400">🔓 PIN 해제</span></button></>)}
          <button onClick={() => setShowSettings(true)} className="w-full flex items-center gap-3 px-4 py-3 border-b border-gray-100 hover:bg-gray-50 text-left"><span className="text-gray-400">⚙️</span><span className="flex-1 text-sm text-gray-600">설정</span><span className="text-gray-300">›</span></button>
          <button onClick={() => setShowFAQ(true)} className="w-full flex items-center gap-3 px-4 py-3 border-b border-gray-100 hover:bg-gray-50 text-left"><span className="text-gray-400">❓</span><span className="flex-1 text-sm text-gray-600">고객센터 / FAQ</span><span className="text-gray-400 text-sm">›</span></button>
          <button onClick={() => setShowTerms(true)} className="w-full flex items-center gap-3 px-4 py-3 border-b border-gray-100 hover:bg-gray-50 text-left"><span className="text-gray-400">📄</span><span className="flex-1 text-sm text-gray-600">이용약관</span><span className="text-gray-400 text-sm">›</span></button>
          <button onClick={() => setShowPrivacy(true)} className="w-full flex items-center gap-3 px-4 py-3 border-b border-gray-100 hover:bg-gray-50 text-left"><span className="text-gray-400">🔒</span><span className="flex-1 text-sm text-gray-600">개인정보처리방침</span><span className="text-gray-400 text-sm">›</span></button>
          <button onClick={() => { if (window.confirm('로그아웃 하시겠습니까?')) onLogout(); }} className="w-full flex items-center gap-3 px-4 py-3 border-b border-gray-100 hover:bg-gray-50 text-left"><span className="text-gray-400">🚪</span><span className="flex-1 text-sm text-gray-600">로그아웃</span></button>
          <button onClick={() => setShowWithdraw(true)} className="w-full flex items-center gap-3 px-4 py-3 border-b border-gray-100 hover:bg-gray-50 text-left"><span className="text-gray-400">🗑️</span><span className="flex-1 text-sm text-red-400">회원탈퇴</span></button>
          <button onClick={handleResetClick} className="w-full flex items-center gap-3 px-4 py-3 hover:bg-gray-50 text-left"><span className="text-gray-400">⚠️</span><span className="flex-1 text-sm text-red-500 font-semibold">처음부터 다시하기</span></button>
        </div>
        <p className="text-center text-xs text-gray-400 mt-3">앱 버전 v2.8.1 (AI머니야)</p>
      </div>

      {/* ═══ DESIRE 로드맵 모달 ═══ */}
      {showDesireRoadmap && (
        <div className="fixed inset-0 bg-black/50 z-50 flex items-end justify-center">
          <div className="bg-white w-full max-w-lg rounded-t-2xl max-h-[90vh] overflow-y-auto">
            <div className="sticky top-0 bg-gradient-to-r from-emerald-500 to-teal-600 p-4 rounded-t-2xl flex items-center z-10"><button onClick={() => setShowDesireRoadmap(false)} className="text-white text-xl mr-3">←</button><div className="flex-1"><h2 className="text-white text-lg font-bold">🏆 도전! DESIRE 로드맵</h2><p className="text-emerald-100 text-xs">현재 {[1,2,3,4,5].filter(s => isStageComplete(s)).length > 0 ? `${[1,2,3,4,5].filter(s => isStageComplete(s)).length}단계 완료` : '시작 전'} · 나의 금융 자유 여정</p></div></div>
            <div className="px-4 py-3 bg-emerald-50"><div className="flex justify-between text-xs mb-1"><span className="text-emerald-700 font-semibold">전체 진행률</span><span className="text-emerald-600 font-bold">{[1,2,3,4,5].filter(s => isStageComplete(s)).length}/6</span></div><div className="w-full h-2.5 bg-emerald-200 rounded-full overflow-hidden"><div className="h-full bg-gradient-to-r from-emerald-400 to-teal-500 rounded-full transition-all duration-500" style={{ width: `${([1,2,3,4,5].filter(s => isStageComplete(s)).length / 6) * 100}%` }} /></div></div>
            <div className="px-4 pt-3 pb-1">
              {!showStoryForm ? (<button onClick={() => setShowStoryForm(true)} className="w-full flex items-center gap-3 p-4 bg-gradient-to-r from-teal-50 to-emerald-50 border-2 border-teal-200 rounded-xl hover:border-teal-400 transition-all"><span className="text-2xl">✉️</span><div className="flex-1 text-left"><p className="text-sm font-bold text-teal-800">나의 DESIRE 사연 보내기</p><p className="text-xs text-teal-600">선정 시 오상열 CFP 1:1 미니상담 + 전자책 선물!</p></div><span className="text-teal-400 text-lg">›</span></button>
              ) : storySubmitted ? (<div className="bg-emerald-50 rounded-xl p-6 text-center border-2 border-emerald-200"><p className="text-4xl mb-3">🎉</p><h4 className="text-lg font-bold text-emerald-700 mb-2">사연이 접수되었습니다!</h4><p className="text-sm text-emerald-600 mb-1">검토 후 선정 결과를 안내드립니다.</p><p className="text-xs text-gray-500 mb-4">선정 시 1:1 미니상담 + 전자책 선물 증정</p><button onClick={resetStoryForm} className="px-6 py-2 bg-emerald-500 text-white text-sm font-semibold rounded-lg">확인</button></div>
              ) : (<div className="bg-white rounded-xl border-2 border-teal-200 overflow-hidden"><div className="bg-gradient-to-r from-teal-500 to-emerald-500 p-4 flex items-center"><button onClick={() => setShowStoryForm(false)} className="text-white text-lg mr-3">←</button><div><h4 className="text-white text-sm font-bold">✉️ 나의 DESIRE 사연 보내기</h4><p className="text-teal-100 text-xs">선정 시 1:1 미니상담 + 전자책 선물!</p></div></div><div className="p-4 space-y-4"><div><label className="block text-xs font-semibold text-gray-700 mb-1">닉네임 <span className="text-red-500">*</span></label><input type="text" value={storyNickname} onChange={e => setStoryNickname(e.target.value)} placeholder="방송에서 사용될 닉네임" className="w-full px-3 py-2.5 border border-gray-200 rounded-lg text-sm focus:border-teal-400 focus:outline-none transition" /></div><div><label className="block text-xs font-semibold text-gray-700 mb-2">DESIRE 단계 <span className="text-red-500">*</span></label><div className="flex flex-wrap gap-2">{DESIRE_CHIP_OPTIONS.map(chip => (<button key={chip.key} onClick={() => setStoryDesireStage(chip.key)} className={`px-3 py-1.5 rounded-full text-xs font-medium border transition-all ${storyDesireStage === chip.key ? 'bg-teal-500 text-white border-teal-500' : 'bg-white text-gray-500 border-gray-200 hover:border-teal-300'}`}>{chip.label}</button>))}</div></div><div><label className="block text-xs font-semibold text-gray-700 mb-1">나의 사연 <span className="text-red-500">*</span></label><textarea value={storyContent} onChange={e => setStoryContent(e.target.value)} placeholder={"현재 재정 상황과 고민을 자유롭게 적어주세요.\n\n예) 카드빚 3000만원, 대출 5000만원으로 매달 이자만 50만원입니다..."} className="w-full px-3 py-2.5 border border-gray-200 rounded-lg text-sm h-32 resize-none focus:border-teal-400 focus:outline-none transition" /><p className="text-xs text-gray-400 mt-1">최소 50자 이상 작성해 주세요 ({storyContent.length}자)</p></div><div><label className="block text-xs font-semibold text-gray-700 mb-1">연락처 (선택)</label><input type="text" value={storyContact} onChange={e => setStoryContact(e.target.value)} placeholder="전화번호 또는 이메일" className="w-full px-3 py-2.5 border border-gray-200 rounded-lg text-sm focus:border-teal-400 focus:outline-none transition" /><p className="text-xs text-gray-400 mt-1">선정 시 연락 및 선물 발송에 사용됩니다</p></div><label className="flex items-start gap-2 cursor-pointer"><input type="checkbox" checked={storyAgree} onChange={e => setStoryAgree(e.target.checked)} className="mt-0.5 accent-teal-500" /><span className="text-xs text-gray-500 leading-relaxed">사연이 방송에 사용될 수 있으며, 개인정보는 방송 제작 목적으로만 사용됩니다.</span></label><button onClick={handleStorySubmit} className="w-full py-3 bg-gradient-to-r from-teal-500 to-emerald-500 text-white text-sm font-bold rounded-xl hover:shadow-lg transition">✉️ 사연 보내기</button><p className="text-xs text-gray-400 text-center leading-relaxed">제출된 사연은 검토 후 선정되며,<br />선정 결과는 앱 알림으로 안내드립니다.</p></div></div>)}
            </div>
            <input ref={photoInputRef} type="file" accept="image/*" capture="environment" className="hidden" onChange={handlePhotoChange} />
            <div className="p-4 space-y-3">
              {DESIRE_STAGES.map((stage) => { const isComplete = isStageComplete(stage.stage); const isExpanded = desireExpandedStage === stage.stage; const isLocked = stage.stage === 6 && !isStageComplete(6); const detail = desireStageDetails[stage.stage]; return (
                <div key={stage.stage} className="rounded-xl overflow-hidden border-2 transition-all" style={{ borderColor: isComplete ? stage.color : '#e5e7eb' }}>
                  <button onClick={() => { if (isLocked) return; setDesireExpandedStage(isExpanded ? null : stage.stage); }} className="w-full flex items-center gap-3 p-3 text-left transition-opacity" style={{ background: `linear-gradient(135deg, ${stage.bgFrom}, ${stage.bgTo})`, opacity: isLocked ? 0.4 : 1 }}><div className="w-10 h-10 rounded-full flex items-center justify-center text-white font-bold text-sm shadow" style={{ background: stage.color }}>{isComplete ? '✓' : stage.letter}</div><div className="flex-1 min-w-0"><div className="flex items-center gap-2"><span className="text-xs font-bold" style={{ color: stage.color }}>STEP {stage.stage}</span>{isComplete && <span className="text-xs bg-green-500 text-white px-1.5 py-0.5 rounded-full">완료</span>}{isLocked && <span className="text-xs">🔒</span>}</div><p className="text-sm font-semibold text-gray-800">{stage.title}</p>{detail && <p className="text-xs text-gray-500 mt-0.5 truncate">{detail.summary}</p>}</div><span className="text-xl">{stage.house}</span>{!isLocked && <span className="text-gray-400 text-sm">{isExpanded ? '▲' : '▼'}</span>}</button>
                  {isExpanded && !isLocked && (<div className="bg-white p-4 border-t border-gray-100">
                    {stage.stage === 1 && (<div className="space-y-2">{(detail?.creditLoans || []).length > 0 ? (<><p className="text-xs text-gray-500 mb-2">📌 고금리 순으로 상환하세요</p>{detail!.creditLoans!.map((loan) => (<label key={`cl-${loan.id}`} className="flex items-center gap-3 p-3 bg-red-50 rounded-lg cursor-pointer hover:bg-red-100 transition"><input type="checkbox" checked={!!desireLoanChecks[`cl-${loan.id}`]} onChange={() => handleLoanCheck(`cl-${loan.id}`)} className="w-5 h-5 rounded accent-red-500" /><div className="flex-1 min-w-0"><p className={`text-sm font-semibold ${desireLoanChecks[`cl-${loan.id}`] ? 'line-through text-gray-400' : 'text-gray-800'}`}>{loan.name}</p><p className="text-xs text-gray-500">{(loan.amount / 10000).toLocaleString()}만원</p></div><span className="text-sm font-bold text-red-600">{loan.rate}%</span></label>))}<p className="text-xs text-gray-400 text-center mt-2">진행: {Object.keys(desireLoanChecks).filter(k => k.startsWith('cl-') && desireLoanChecks[k]).length}/{detail!.creditLoans!.length}건 완료</p></>) : (<div className="text-center py-4"><p className="text-3xl mb-2">✅</p><p className="text-sm text-green-600 font-semibold">신용대출이 없습니다!</p></div>)}</div>)}
                    {stage.stage === 2 && detail?.emergencyFund && (<div className="space-y-3"><div className="flex justify-between text-xs text-gray-600"><span>현재: <strong className="text-orange-600">{(detail.emergencyFund.current / 10000).toLocaleString()}만원</strong></span><span>목표: <strong>{(detail.emergencyFund.target / 10000).toLocaleString()}만원</strong></span></div><div className="w-full h-4 bg-gray-200 rounded-full overflow-hidden"><div className="h-full rounded-full transition-all duration-700" style={{ width: `${Math.min(100, detail.emergencyFund.target > 0 ? (detail.emergencyFund.current / detail.emergencyFund.target) * 100 : 0)}%`, background: `linear-gradient(90deg, #ea580c, #f97316)` }} /></div><p className="text-center text-xs text-gray-500">달성률 <strong className="text-orange-600">{detail.emergencyFund.target > 0 ? Math.round((detail.emergencyFund.current / detail.emergencyFund.target) * 100) : 0}%</strong>{detail.emergencyFund.secured && ' ✅'}</p></div>)}
                    {stage.stage === 2 && !detail?.emergencyFund && (<div className="text-center py-4 text-gray-400 text-sm">금융집짓기에서 비상예비자금을 설정해주세요</div>)}
                    {stage.stage === 3 && detail?.savings && (<div className="space-y-3"><div className="grid grid-cols-2 gap-2"><div className="bg-yellow-50 rounded-lg p-3 text-center"><p className="text-xs text-gray-500">월 저축투자</p><p className="text-lg font-bold text-yellow-700">{(detail.savings.monthlySaving / 10000).toLocaleString()}<span className="text-xs font-normal">만원</span></p></div><div className="bg-yellow-50 rounded-lg p-3 text-center"><p className="text-xs text-gray-500">월 노후연금</p><p className="text-lg font-bold text-yellow-700">{(detail.savings.monthlyPension / 10000).toLocaleString()}<span className="text-xs font-normal">만원</span></p></div></div>{detail.savings.irregularIncome > 0 && (<div className="bg-amber-50 rounded-lg p-3 text-center"><p className="text-xs text-gray-500">비정기 수입</p><p className="text-base font-bold text-amber-700">{(detail.savings.irregularIncome / 10000).toLocaleString()}만원</p></div>)}<p className="text-xs text-gray-400 text-center">합계: 월 {((detail.savings.monthlySaving + detail.savings.monthlyPension) / 10000).toLocaleString()}만원</p></div>)}
                    {stage.stage === 3 && !detail?.savings && (<div className="text-center py-4 text-gray-400 text-sm">금융집짓기에서 저축/연금을 설정해주세요</div>)}
                    {stage.stage === 4 && detail?.investment && (<div className="space-y-3"><div className="text-center mb-2"><p className="text-3xl font-bold text-blue-600">{(detail.investment.financialAssets / 100000000).toFixed(1)}<span className="text-sm font-normal text-gray-500">억원</span></p><p className="text-xs text-gray-400">목표: 10억원</p></div><div className="w-full h-4 bg-gray-200 rounded-full overflow-hidden"><div className="h-full rounded-full transition-all duration-700" style={{ width: `${Math.min(100, (detail.investment.financialAssets / detail.investment.target) * 100)}%`, background: `linear-gradient(90deg, #2563eb, #3b82f6)` }} /></div><p className="text-center text-xs text-gray-500">달성률 <strong className="text-blue-600">{Math.round((detail.investment.financialAssets / detail.investment.target) * 100)}%</strong></p></div>)}
                    {stage.stage === 4 && !detail?.investment && (<div className="text-center py-4 text-gray-400 text-sm">금융집짓기에서 금융자산을 입력해주세요</div>)}
                    {stage.stage === 5 && (<div className="space-y-2">{(detail?.mortgageLoans || []).length > 0 ? (<><p className="text-xs text-gray-500 mb-2">📌 담보대출 상환 계획</p>{detail!.mortgageLoans!.map((loan) => (<label key={`ml-${loan.id}`} className="flex items-center gap-3 p-3 bg-purple-50 rounded-lg cursor-pointer hover:bg-purple-100 transition"><input type="checkbox" checked={!!desireLoanChecks[`ml-${loan.id}`]} onChange={() => handleLoanCheck(`ml-${loan.id}`)} className="w-5 h-5 rounded accent-purple-500" /><div className="flex-1 min-w-0"><p className={`text-sm font-semibold ${desireLoanChecks[`ml-${loan.id}`] ? 'line-through text-gray-400' : 'text-gray-800'}`}>{loan.name}</p><p className="text-xs text-gray-500">{(loan.amount / 10000).toLocaleString()}만원</p></div><span className="text-sm font-bold text-purple-600">{loan.rate}%</span></label>))}<p className="text-xs text-gray-400 text-center mt-2">진행: {Object.keys(desireLoanChecks).filter(k => k.startsWith('ml-') && desireLoanChecks[k]).length}/{detail!.mortgageLoans!.length}건 완료</p></>) : (<div className="text-center py-4"><p className="text-3xl mb-2">✅</p><p className="text-sm text-green-600 font-semibold">담보대출이 없습니다!</p></div>)}</div>)}
                    {stage.stage === 6 && (<div className="text-center py-6">{!giftOpened ? (<><p className="text-5xl mb-3 animate-bounce">🎁</p><h4 className="text-lg font-bold text-emerald-700 mb-2">축하드립니다!</h4><p className="text-sm text-gray-600 mb-1">DESIRE 6단계를 모두 완료하셨습니다!</p><p className="text-sm text-gray-600 mb-4">초가집에서 시작한 금융 여정이<br />마침내 <strong className="text-emerald-600">고급주택</strong>에 도달했습니다!</p><button onClick={handleOpenGift} className="px-8 py-3 bg-gradient-to-r from-amber-400 to-amber-500 text-white text-sm font-bold rounded-xl shadow-lg hover:shadow-xl transition transform hover:scale-105">🎁 선물함 열기</button></>) : (<><p className="text-5xl mb-3">🏰</p><h4 className="text-lg font-bold text-emerald-700 mb-2">경제적 자유 달성!</h4><p className="text-sm text-gray-500">당신의 금융집이 완성되었습니다 🎉</p></>)}</div>)}
                    {stage.stage <= 5 && (<div className="mt-4 pt-3 border-t border-gray-100 space-y-3"><button onClick={() => handleDesireComplete(stage.stage)} className={`w-full py-3 rounded-xl text-sm font-bold transition flex items-center justify-center gap-2 ${desireCompleted[stage.stage] ? 'bg-green-500 text-white' : 'bg-gray-100 text-gray-600 hover:bg-gray-200'}`}>{desireCompleted[stage.stage] ? '✅ 완료!' : '☐ 완료 체크'}</button><button onClick={() => handlePhotoAttach(stage.stage)} className="w-full py-2.5 rounded-xl text-xs font-semibold border-2 border-dashed border-gray-300 text-gray-500 hover:border-gray-400 hover:text-gray-600 transition flex items-center justify-center gap-2">📷 인증샷 첨부</button>{desirePhotos[stage.stage] && (<div className="relative"><img src={desirePhotos[stage.stage]} alt="인증샷" className="w-full h-40 object-cover rounded-xl border border-gray-200" onClick={() => window.open(desirePhotos[stage.stage], '_blank')} style={{ cursor: 'pointer' }} /><button onClick={() => { const next = { ...desirePhotos }; delete next[stage.stage]; setDesirePhotos(next); localStorage.setItem('desirePhotos', JSON.stringify(next)); }} className="absolute top-2 right-2 w-6 h-6 bg-black/50 rounded-full text-white text-xs flex items-center justify-center">✕</button></div>)}<p className="text-xs text-gray-400 text-center">📍 {stage.dataSource}</p></div>)}
                  </div>)}
                </div>
              ); })}
            </div>
            <div className="px-4 pb-6"><div className="bg-gray-50 rounded-xl p-4 text-center"><p className="text-xs text-gray-500 mb-2">나의 금융집 진화</p><div className="flex items-center justify-center gap-1 text-2xl flex-wrap">{DESIRE_STAGES.map((s, i) => (<span key={i} className={`transition-opacity ${isStageComplete(s.stage) ? '' : 'opacity-30'}`}>{i > 0 && <span className="text-sm text-gray-400 mx-0.5">→</span>}{s.house}</span>))}</div></div></div>
          </div>
        </div>
      )}
      {/* 축하 모달 */}
      {showCelebration && (<div className="fixed inset-0 bg-black/60 z-[60] flex items-center justify-center p-4" onClick={() => setShowCelebration(false)}><div className="bg-white rounded-2xl p-6 max-w-sm w-full text-center relative overflow-hidden" onClick={e => e.stopPropagation()}><div className="absolute inset-0 pointer-events-none">{Array.from({ length: 30 }).map((_, i) => (<div key={i} className="absolute w-2 h-2 rounded-full animate-ping" style={{ left: `${Math.random() * 100}%`, top: `${Math.random() * 100}%`, background: ['#dc2626', '#ea580c', '#ca8a04', '#2563eb', '#7c3aed', '#059669', '#f59e0b', '#ec4899'][i % 8], animationDelay: `${Math.random() * 2}s`, animationDuration: `${1 + Math.random() * 2}s` }} />))}</div><p className="text-6xl mb-4 relative">🎊</p><h3 className="text-xl font-bold text-gray-800 mb-2 relative">🎉 DESIRE 완주! 🎉</h3><p className="text-sm text-gray-600 mb-2 relative">금융 자유를 향한 모든 단계를 완료하셨습니다!</p><p className="text-sm text-gray-500 mb-4 relative">당신의 금융집이 완성되었어요! 🏰</p><div className="flex items-center justify-center gap-1 text-2xl mb-4 relative"><span>🏚️</span><span className="text-sm">→</span><span>🏡</span><span className="text-sm">→</span><span>🏠</span><span className="text-sm">→</span><span>🏢</span><span className="text-sm">→</span><span>🏛️</span><span className="text-sm">→</span><span>🏰</span></div><button onClick={() => setShowCelebration(false)} className="px-8 py-3 bg-gradient-to-r from-amber-400 to-amber-500 text-white font-bold rounded-xl relative">감사합니다! 🙏</button></div></div>)}

      {/* ═══ 멤버십 플랜 모달 ═══ */}
      {showMembership && (<div className="fixed inset-0 bg-black/50 z-50 flex items-end justify-center"><div className="bg-white w-full max-w-lg rounded-t-2xl max-h-[90vh] overflow-y-auto">
        <div className="sticky top-0 bg-gradient-to-r from-purple-600 to-indigo-600 p-4 rounded-t-2xl flex items-center"><button onClick={closeMembership} className="text-white text-xl mr-3">←</button><div><h2 className="text-white text-lg font-bold">👑 멤버십 플랜</h2><p className="text-purple-200 text-xs">나에게 맞는 플랜을 선택하세요</p></div></div>
        {membershipStep === 'list' && (<><div className="flex mx-4 mt-3 bg-gray-100 rounded-xl p-1"><button onClick={() => setMembershipTab('general')} className={`flex-1 py-2.5 rounded-lg text-sm font-bold transition-all ${membershipTab === 'general' ? 'bg-white text-purple-600 shadow-sm' : 'text-gray-400'}`}>🏠 일반인</button><button onClick={() => setMembershipTab('fp')} className={`flex-1 py-2.5 rounded-lg text-sm font-bold transition-all ${membershipTab === 'fp' ? 'bg-white text-purple-600 shadow-sm' : 'text-gray-400'}`}>💼 금융전문가(FP)</button></div>
          <div className="p-4 space-y-3">{(MEMBERSHIP_PLANS[membershipTab] || []).map(plan => (<div key={plan.tier} className={`bg-white rounded-xl border-2 p-4 ${plan.highlight ? 'border-purple-400 shadow-lg' : 'border-gray-200'} relative`}>{plan.highlight && <span className="absolute -top-2.5 right-4 bg-purple-500 text-white text-xs font-bold px-3 py-0.5 rounded-full">추천</span>}<div className="flex items-center gap-2 mb-2"><span className="text-xl">{plan.badge}</span><span className="text-sm font-bold text-gray-800">{plan.tier}</span>{plan.current && <span className="text-xs bg-gray-200 text-gray-500 px-2 py-0.5 rounded">현재</span>}</div><div className="mb-2">{plan.price === 0 ? (<span className="text-2xl font-extrabold text-gray-800">{plan.priceDisplay}</span>) : (<><span className="text-2xl font-extrabold text-gray-800">₩{plan.priceDisplay}</span><span className="text-sm text-gray-500">/월</span></>)}</div><div className="space-y-1 mb-3">{plan.benefits.map((b, i) => (<p key={i} className="text-xs text-gray-600">✓ {b}</p>))}</div><button onClick={() => handleSelectPlan(plan)} className={`w-full py-2.5 rounded-lg text-sm font-bold transition ${plan.current ? 'bg-gray-100 text-gray-400' : plan.highlight ? 'bg-purple-500 text-white hover:bg-purple-600' : 'bg-gray-800 text-white hover:bg-gray-700'}`}>{plan.current ? '현재 플랜' : '선택하기'}</button></div>))}</div></>)}
        {membershipStep === 'cycle' && selectedMembershipPlan && (<div className="p-4"><button onClick={() => setMembershipStep('list')} className="text-sm text-gray-500 mb-4">← 뒤로</button><h3 className="text-lg font-bold text-gray-800 mb-4">{selectedMembershipPlan.badge} {selectedMembershipPlan.tier} 결제 주기</h3><div className="space-y-3"><button onClick={() => handleSelectCycle('monthly')} className="w-full p-4 border-2 border-gray-200 rounded-xl text-left hover:border-purple-400 transition"><p className="text-sm font-bold text-gray-800">월간 결제</p><p className="text-xl font-extrabold text-purple-600">₩{selectedMembershipPlan.priceDisplay}/월</p></button><button onClick={() => handleSelectCycle('annual')} className="w-full p-4 border-2 border-purple-400 rounded-xl text-left bg-purple-50 relative"><span className="absolute -top-2 right-4 bg-red-500 text-white text-xs font-bold px-2 py-0.5 rounded-full">17% 할인</span><p className="text-sm font-bold text-gray-800">연간 결제</p><p className="text-xl font-extrabold text-purple-600">₩{selectedMembershipPlan.annualDisplay}/년</p><p className="text-xs text-gray-500">월 ₩{selectedMembershipPlan.annualMonthly} 환산</p></button></div></div>)}
        {membershipStep === 'payment' && selectedMembershipPlan && billingCycle && (<div className="p-4"><button onClick={() => setMembershipStep('cycle')} className="text-sm text-gray-500 mb-4">← 뒤로</button><div className="bg-purple-50 rounded-xl p-4 mb-4"><p className="text-sm font-bold text-purple-800">{selectedMembershipPlan.badge} {selectedMembershipPlan.tier} · {billingCycle === 'monthly' ? '월간' : '연간'}</p><p className="text-2xl font-extrabold text-purple-600">₩{billingCycle === 'monthly' ? selectedMembershipPlan.priceDisplay : selectedMembershipPlan.annualDisplay}</p></div><div className="space-y-3"><div><label className="block text-xs font-semibold text-gray-700 mb-1">카드번호</label><input type="text" value={cardNumber} onChange={e => setCardNumber(formatCardNumber(e.target.value))} placeholder="0000-0000-0000-0000" className="w-full px-3 py-2.5 border border-gray-200 rounded-lg text-sm" /></div><div className="flex gap-3"><div className="flex-1"><label className="block text-xs font-semibold text-gray-700 mb-1">유효기간</label><input type="text" value={cardExpiry} onChange={e => setCardExpiry(formatExpiry(e.target.value))} placeholder="MM/YY" className="w-full px-3 py-2.5 border border-gray-200 rounded-lg text-sm" /></div><div className="flex-1"><label className="block text-xs font-semibold text-gray-700 mb-1">CVC</label><input type="password" value={cardCvc} onChange={e => setCardCvc(e.target.value.replace(/\D/g, '').slice(0, 3))} placeholder="000" className="w-full px-3 py-2.5 border border-gray-200 rounded-lg text-sm" /></div></div><div><label className="block text-xs font-semibold text-gray-700 mb-1">카드 소유자</label><input type="text" value={cardHolder} onChange={e => setCardHolder(e.target.value)} placeholder="홍길동" className="w-full px-3 py-2.5 border border-gray-200 rounded-lg text-sm" /></div><button onClick={handlePay} disabled={isPayProcessing} className="w-full py-3 bg-purple-500 text-white font-bold rounded-xl hover:bg-purple-600 disabled:bg-gray-300 transition">{isPayProcessing ? '결제 처리 중...' : '결제하기'}</button></div></div>)}
        {membershipStep === 'done' && (<div className="p-8 text-center"><p className="text-5xl mb-4">🎉</p><h3 className="text-xl font-bold text-gray-800 mb-2">결제 완료!</h3><p className="text-sm text-gray-600 mb-6">{selectedMembershipPlan?.tier} 플랜이 활성화되었습니다.</p><button onClick={closeMembership} className="px-8 py-3 bg-purple-500 text-white font-bold rounded-xl">확인</button></div>)}
      </div></div>)}

      {/* ═══ 온라인강좌 107강 모달 ═══ */}
      {showOnlineCourse && (<div className="fixed inset-0 bg-black/50 z-50 flex items-end justify-center"><div className="bg-white w-full max-w-lg rounded-t-2xl max-h-[90vh] overflow-y-auto">
        <div className="sticky top-0 bg-gradient-to-r from-cyan-500 to-teal-500 p-4 rounded-t-2xl flex items-center"><button onClick={() => setShowOnlineCourse(false)} className="text-white text-xl mr-3">←</button><div><h2 className="text-white text-lg font-bold">🎓 온라인강좌 107강</h2><p className="text-cyan-100 text-xs">금융집짓기® 완전정복 과정</p></div></div>
        <div className="p-4"><div className="bg-gradient-to-br from-cyan-50 to-teal-50 border border-cyan-200 rounded-xl p-5 mb-4"><div className="flex items-center gap-3 mb-3"><div className="w-12 h-12 bg-gradient-to-br from-cyan-400 to-teal-500 rounded-xl flex items-center justify-center text-white text-xl shadow-md">🎓</div><div><p className="text-sm font-bold text-gray-800">금융집짓기® 완전정복</p><p className="text-xs text-gray-500">107개 강의 · 총 50시간+ · 무제한 반복 수강</p></div></div><p className="text-xs text-gray-600 leading-relaxed">재무설계의 A~Z를 체계적으로 배우는 온라인 강좌입니다. 부채관리부터 투자, 은퇴설계까지 금융집짓기® 방법론의 모든 것을 담았습니다.</p></div>
          <div className="space-y-3"><button onClick={() => window.open('https://link.payple.kr/NzcxOjc2ODQ3NzY2NjM3Mjg2', '_blank')} className="w-full p-4 bg-gradient-to-r from-blue-500 to-blue-600 text-white rounded-xl text-left hover:shadow-lg transition"><p className="text-sm font-bold">📚 온라인강좌만 (107강)</p><p className="text-xl font-extrabold">₩290,000</p><p className="text-xs opacity-80">107개 강의 무제한 수강</p></button><button onClick={() => window.open('https://link.payple.kr/NzcxOjc2ODQ3NzY4Mzc5MTUx', '_blank')} className="w-full p-4 bg-gradient-to-r from-purple-500 to-indigo-600 text-white rounded-xl text-left hover:shadow-lg transition relative"><span className="absolute -top-2 right-4 bg-red-500 text-white text-xs font-bold px-2 py-0.5 rounded-full">추천</span><p className="text-sm font-bold">📚+📖 강좌 + 전자책 세트</p><p className="text-xl font-extrabold">₩300,000</p><p className="text-xs opacity-80">107강 + 금융집짓기® 전자책 (₩12,900 상당)</p></button><button onClick={() => window.open('https://link.payple.kr/NzcxOjc2ODQ3NzcwMjQ2MzQw', '_blank')} className="w-full p-4 bg-gradient-to-r from-amber-500 to-amber-600 text-white rounded-xl text-left hover:shadow-lg transition"><p className="text-sm font-bold">📚+📖+🎓 올인원 패키지</p><p className="text-xl font-extrabold">₩590,000</p><p className="text-xs opacity-80">107강 + 전자책 + 월례 ZOOM 세미나 1년</p></button></div>
        </div>
      </div></div>)}

      {/* ═══ 전자책 모달 ═══ */}
      {showEbook && (<div className="fixed inset-0 bg-black/50 z-50 flex items-end justify-center"><div className="bg-white w-full max-w-lg rounded-t-2xl max-h-[90vh] overflow-y-auto">
        <div className="sticky top-0 bg-gradient-to-r from-orange-500 to-orange-600 p-4 rounded-t-2xl flex items-center"><button onClick={() => setShowEbook(false)} className="text-white text-xl mr-3">←</button><div><h2 className="text-white text-lg font-bold">📖 금융집짓기® 전자책</h2><p className="text-orange-100 text-xs">오상열 CFP의 재무설계 가이드</p></div></div>
        <div className="p-4"><div className="flex gap-4 mb-4"><img src={EBOOK_COVER_URL} alt="전자책 표지" className="w-28 h-40 object-cover rounded-xl shadow-md" /><div className="flex-1"><p className="text-lg font-bold text-gray-800 mb-1">금융집짓기®</p><p className="text-sm text-gray-500 mb-2">오상열 CFP 저</p><p className="text-xs text-gray-600 leading-relaxed">20년 경력 재무설계 전문가의 노하우를 담은 금융집짓기® 전자책입니다. 부채관리부터 투자, 은퇴설계까지 체계적인 재무설계 방법론을 소개합니다.</p></div></div>
          <button onClick={() => window.open('https://link.payple.kr/NzcxOjc2ODQ3NzcxMjU1NTMw', '_blank')} className="w-full py-3 bg-gradient-to-r from-orange-500 to-orange-600 text-white font-bold rounded-xl hover:shadow-lg transition">₩12,900 구매하기</button>
        </div>
      </div></div>)}

      {/* ═══ 공유 모달 ═══ */}
      {showShare && (<div className="fixed inset-0 bg-black/50 z-50 flex items-end justify-center"><div className="bg-white w-full max-w-lg rounded-t-2xl max-h-[90vh] overflow-y-auto">
        <div className="sticky top-0 bg-gradient-to-r from-violet-500 to-violet-600 p-4 rounded-t-2xl flex items-center"><button onClick={() => setShowShare(false)} className="text-white text-xl mr-3">←</button><div><h2 className="text-white text-lg font-bold">🔗 친구에게 공유하기</h2><p className="text-violet-100 text-xs">AI머니야를 친구에게 알려주세요</p></div></div>
        <div className="p-4"><div className="bg-violet-50 border border-violet-200 rounded-xl p-4 mb-4 text-center"><p className="text-sm text-gray-600 mb-2">공유 링크</p><p className="text-sm font-mono text-violet-600 bg-white px-3 py-2 rounded-lg border">{SHARE_URL}</p></div>
          <div className="grid grid-cols-2 gap-3"><button onClick={() => handleShare('copy')} className="flex items-center gap-2 p-3 bg-gray-100 rounded-xl hover:bg-gray-200 transition"><span>📋</span><span className="text-sm font-semibold text-gray-700">링크 복사</span></button><button onClick={() => handleShare('kakao')} className="flex items-center gap-2 p-3 bg-yellow-50 rounded-xl hover:bg-yellow-100 transition"><span>💬</span><span className="text-sm font-semibold text-gray-700">카카오톡</span></button><button onClick={() => handleShare('sms')} className="flex items-center gap-2 p-3 bg-green-50 rounded-xl hover:bg-green-100 transition"><span>📱</span><span className="text-sm font-semibold text-gray-700">문자 전송</span></button><button onClick={() => handleShare('email')} className="flex items-center gap-2 p-3 bg-blue-50 rounded-xl hover:bg-blue-100 transition"><span>📧</span><span className="text-sm font-semibold text-gray-700">이메일</span></button></div>
          <button onClick={() => handleShare('native')} className="w-full mt-3 py-3 bg-violet-500 text-white font-bold rounded-xl hover:bg-violet-600 transition">📤 다른 앱으로 공유</button>
        </div>
      </div></div>)}

      {/* ═══ 설정 모달 ═══ */}
      {showSettings && (<div className="fixed inset-0 bg-black/50 z-50 flex items-end justify-center"><div className="bg-white w-full max-w-lg rounded-t-2xl max-h-[90vh] overflow-y-auto">
        <div className="sticky top-0 bg-white border-b p-4 rounded-t-2xl flex items-center"><button onClick={() => setShowSettings(false)} className="text-gray-500 text-xl mr-3">←</button><h2 className="text-lg font-bold text-gray-800">⚙️ 설정</h2></div>
        <div className="p-4 space-y-4">
          <div><h3 className="text-xs font-bold text-gray-400 uppercase mb-2">🔔 알림</h3><div className="bg-white rounded-xl border border-gray-200 divide-y"><div className="flex items-center justify-between px-4 py-3"><span className="text-sm text-gray-700">푸시 알림</span><button onClick={() => { setSettingNotification(!settingNotification); localStorage.setItem('moneya_setting_notification', String(!settingNotification)); }} className={`w-11 h-6 rounded-full transition ${settingNotification ? 'bg-blue-500' : 'bg-gray-300'}`}><div className={`w-5 h-5 bg-white rounded-full shadow transition-transform ${settingNotification ? 'translate-x-5' : 'translate-x-0.5'}`} /></button></div><div className="flex items-center justify-between px-4 py-3"><span className="text-sm text-gray-700">매일 지출 리마인더</span><button onClick={() => { setSettingDailyReminder(!settingDailyReminder); localStorage.setItem('moneya_setting_dailyReminder', String(!settingDailyReminder)); }} className={`w-11 h-6 rounded-full transition ${settingDailyReminder ? 'bg-blue-500' : 'bg-gray-300'}`}><div className={`w-5 h-5 bg-white rounded-full shadow transition-transform ${settingDailyReminder ? 'translate-x-5' : 'translate-x-0.5'}`} /></button></div><div className="flex items-center justify-between px-4 py-3"><span className="text-sm text-gray-700">효과음</span><button onClick={() => { setSettingSound(!settingSound); localStorage.setItem('moneya_setting_sound', String(!settingSound)); }} className={`w-11 h-6 rounded-full transition ${settingSound ? 'bg-blue-500' : 'bg-gray-300'}`}><div className={`w-5 h-5 bg-white rounded-full shadow transition-transform ${settingSound ? 'translate-x-5' : 'translate-x-0.5'}`} /></button></div></div></div>
          <div><h3 className="text-xs font-bold text-gray-400 uppercase mb-2">🖥️ 화면</h3><div className="bg-white rounded-xl border border-gray-200"><div className="flex items-center justify-between px-4 py-3"><span className="text-sm text-gray-700">금액 단위</span><div className="flex bg-gray-100 rounded-lg p-0.5"><button onClick={() => { setSettingAmountUnit('만원'); localStorage.setItem('moneya_setting_amountUnit', '만원'); }} className={`px-3 py-1 text-xs rounded-md transition ${settingAmountUnit === '만원' ? 'bg-white text-blue-600 shadow-sm font-bold' : 'text-gray-400'}`}>만원</button><button onClick={() => { setSettingAmountUnit('원'); localStorage.setItem('moneya_setting_amountUnit', '원'); }} className={`px-3 py-1 text-xs rounded-md transition ${settingAmountUnit === '원' ? 'bg-white text-blue-600 shadow-sm font-bold' : 'text-gray-400'}`}>원</button></div></div></div></div>
          <div><h3 className="text-xs font-bold text-gray-400 uppercase mb-2">🔒 보안</h3><div className="bg-white rounded-xl border border-gray-200"><div className="flex items-center justify-between px-4 py-3"><span className="text-sm text-gray-700">생체 인증</span><button onClick={() => { setSettingBioAuth(!settingBioAuth); localStorage.setItem('moneya_setting_bioAuth', String(!settingBioAuth)); }} className={`w-11 h-6 rounded-full transition ${settingBioAuth ? 'bg-blue-500' : 'bg-gray-300'}`}><div className={`w-5 h-5 bg-white rounded-full shadow transition-transform ${settingBioAuth ? 'translate-x-5' : 'translate-x-0.5'}`} /></button></div></div></div>
          <div><h3 className="text-xs font-bold text-gray-400 uppercase mb-2">💾 데이터 관리</h3><div className="bg-white rounded-xl border border-gray-200"><button onClick={() => { localStorage.removeItem('financialHouseData_cache'); setShowCacheClearDone(true); setTimeout(() => setShowCacheClearDone(false), 2000); }} className="w-full flex items-center justify-between px-4 py-3 text-left"><span className="text-sm text-gray-700">캐시 삭제</span>{showCacheClearDone ? <span className="text-xs text-green-500 font-bold">✅ 완료</span> : <span className="text-gray-400 text-sm">›</span>}</button></div></div>
          <div><h3 className="text-xs font-bold text-gray-400 uppercase mb-2">ℹ️ 앱 정보</h3><div className="bg-white rounded-xl border border-gray-200 divide-y"><div className="flex items-center justify-between px-4 py-3"><span className="text-sm text-gray-700">버전</span><span className="text-sm text-gray-400">v2.8.1</span></div><div className="flex items-center justify-between px-4 py-3"><span className="text-sm text-gray-700">개발</span><span className="text-sm text-gray-400">오원트금융연구소</span></div></div></div>
        </div>
      </div></div>)}

      {/* ═══ FAQ 모달 ═══ */}
      {showFAQ && (<div className="fixed inset-0 bg-black/50 z-50 flex items-end justify-center"><div className="bg-white w-full max-w-lg rounded-t-2xl max-h-[90vh] overflow-y-auto">
        <div className="sticky top-0 bg-white border-b p-4 rounded-t-2xl flex items-center"><button onClick={() => setShowFAQ(false)} className="text-gray-500 text-xl mr-3">←</button><h2 className="text-lg font-bold text-gray-800">❓ 고객센터 / FAQ</h2></div>
        <div className="p-4 space-y-2">{FAQ_DATA.map((item, idx) => (<div key={idx} className="border border-gray-200 rounded-xl overflow-hidden"><button onClick={() => setOpenFaqIndex(openFaqIndex === idx ? null : idx)} className="w-full flex items-center justify-between px-4 py-3 text-left hover:bg-gray-50"><span className="text-sm font-semibold text-gray-700 flex-1">{item.q}</span><span className="text-gray-400">{openFaqIndex === idx ? '▲' : '▼'}</span></button>{openFaqIndex === idx && (<div className="px-4 pb-3 text-sm text-gray-600 bg-gray-50">{item.a}</div>)}</div>))}</div>
      </div></div>)}

      {/* ═══ 이용약관 모달 ═══ */}
      {showTerms && (<div className="fixed inset-0 bg-black/50 z-50 flex items-end justify-center"><div className="bg-white w-full max-w-lg rounded-t-2xl max-h-[90vh] overflow-y-auto">
        <div className="sticky top-0 bg-white border-b p-4 rounded-t-2xl flex items-center"><button onClick={() => setShowTerms(false)} className="text-gray-500 text-xl mr-3">←</button><h2 className="text-lg font-bold text-gray-800">📄 이용약관</h2></div>
        <div className="p-4 text-sm text-gray-600 space-y-4 leading-relaxed"><h3 className="font-bold text-gray-800">제1조 (목적)</h3><p>이 약관은 오원트금융연구소(이하 "회사")가 제공하는 AI머니야 서비스(이하 "서비스")의 이용 조건 및 절차에 관한 사항을 규정함을 목적으로 합니다.</p><h3 className="font-bold text-gray-800">제2조 (정의)</h3><p>"서비스"란 회사가 제공하는 AI 기반 재무관리 및 금융집짓기® 관련 일체의 서비스를 의미합니다.</p><h3 className="font-bold text-gray-800">제3조 (약관의 효력)</h3><p>본 약관은 서비스를 이용하고자 하는 모든 이용자에 대하여 그 효력이 발생합니다.</p></div>
      </div></div>)}

      {/* ═══ 개인정보처리방침 모달 ═══ */}
      {showPrivacy && (<div className="fixed inset-0 bg-black/50 z-50 flex items-end justify-center"><div className="bg-white w-full max-w-lg rounded-t-2xl max-h-[90vh] overflow-y-auto">
        <div className="sticky top-0 bg-white border-b p-4 rounded-t-2xl flex items-center"><button onClick={() => setShowPrivacy(false)} className="text-gray-500 text-xl mr-3">←</button><h2 className="text-lg font-bold text-gray-800">🔒 개인정보처리방침</h2></div>
        <div className="p-4 text-sm text-gray-600 space-y-4 leading-relaxed"><h3 className="font-bold text-gray-800">1. 수집하는 개인정보</h3><p>회사는 서비스 제공을 위해 이메일, 이름, 재무정보(소득, 자산, 부채) 등을 수집합니다.</p><h3 className="font-bold text-gray-800">2. 개인정보의 이용목적</h3><p>수집된 개인정보는 맞춤형 재무설계 서비스 제공, 서비스 개선 등에 활용됩니다.</p><h3 className="font-bold text-gray-800">3. 개인정보의 보관</h3><p>회원 탈퇴 시 모든 개인정보는 즉시 파기됩니다.</p></div>
      </div></div>)}

      {/* ═══ 회원탈퇴 모달 ═══ */}
      {showWithdraw && (<div className="fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4"><div className="bg-white rounded-2xl max-w-sm w-full p-6 text-center"><p className="text-4xl mb-3">⚠️</p><h3 className="text-lg font-bold text-gray-800 mb-2">회원 탈퇴</h3><p className="text-sm text-gray-600 mb-1">탈퇴 시 모든 데이터가 삭제됩니다.</p><p className="text-sm text-red-500 font-semibold mb-4">이 작업은 되돌릴 수 없습니다.</p><div className="flex gap-3"><button onClick={() => setShowWithdraw(false)} className="flex-1 py-2.5 bg-gray-100 text-gray-600 rounded-lg font-semibold">취소</button><button onClick={() => { setShowWithdraw(false); onLogout(); }} className="flex-1 py-2.5 bg-red-500 text-white rounded-lg font-semibold">탈퇴</button></div></div></div>)}

      {/* ═══ 초기화 확인 모달 ═══ */}
      {showResetConfirm && (<div className="fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4"><div className="bg-white rounded-2xl max-w-sm w-full p-6 text-center"><p className="text-4xl mb-3">⚠️</p><h3 className="text-lg font-bold text-gray-800 mb-2">처음부터 다시하기</h3><p className="text-sm text-gray-600 mb-4">모든 재무설계 데이터가 초기화됩니다.<br />이 작업은 되돌릴 수 없습니다.</p><div className="flex gap-3"><button onClick={() => setShowResetConfirm(false)} className="flex-1 py-2.5 bg-gray-100 text-gray-600 rounded-lg font-semibold">취소</button><button onClick={handleResetConfirm} className="flex-1 py-2.5 bg-red-500 text-white rounded-lg font-semibold">초기화</button></div></div></div>)}

      {/* ═══ 프로필 편집 모달 ═══ */}
      {showProfileEdit && (<div className="fixed inset-0 bg-black/50 z-50 flex items-end justify-center"><div className="bg-white w-full max-w-lg rounded-t-2xl max-h-[90vh] overflow-y-auto">
        <div className="sticky top-0 bg-white border-b p-4 rounded-t-2xl flex items-center"><button onClick={() => setShowProfileEdit(false)} className="text-gray-500 text-xl mr-3">←</button><h2 className="text-lg font-bold text-gray-800">프로필 편집</h2></div>
        <div className="p-4 space-y-4"><div><label className="block text-xs font-semibold text-gray-700 mb-1">이름</label><input type="text" value={editName} onChange={e => setEditName(e.target.value)} className="w-full px-3 py-2.5 border border-gray-200 rounded-lg text-sm" /></div><button onClick={() => setShowProfileEdit(false)} className="w-full py-3 bg-blue-500 text-white font-bold rounded-xl">저장</button></div>
      </div></div>)}

      {/* ═══ 전문가 강의·상담 모달 ═══ */}
      {showExpertConsult && (<div className="fixed inset-0 bg-black/50 z-50 flex items-end justify-center"><div className="bg-white w-full max-w-lg rounded-t-2xl max-h-[90vh] overflow-y-auto">
        <div className="sticky top-0 bg-gradient-to-r from-amber-500 to-amber-600 p-4 rounded-t-2xl flex items-center z-10"><button onClick={closeExpertConsultModal} className="text-white text-xl mr-3">←</button><div className="flex-1"><h2 className="text-white text-lg font-bold">👨‍🏫 오상열 대표 강의·상담</h2><p className="text-amber-100 text-xs">20년 경력 재무설계 전문가</p></div></div>
        {consultView === 'list' && (<div className="p-4 space-y-3">
          <div className="bg-amber-50 border border-amber-200 rounded-xl p-4 flex items-center gap-3 mb-2"><img src={PROFILE_IMAGE_URL} alt="오상열 CFP" className="w-12 h-12 rounded-full object-cover border-2 border-amber-300" /><div><p className="text-sm font-bold text-amber-800">오상열 CFP</p><p className="text-xs text-amber-600">오원트금융연구소 대표</p><p className="text-xs text-gray-500 mt-0.5">500회+ 강의 · 2000건+ 상담</p></div></div>
          <p className="text-xs text-gray-500 font-bold">📚 강의</p>
          {CONSULT_TYPES.filter(t => t.category === 'lecture').map(type => (<button key={type.id} onClick={() => handleConsultSelectType(type)} className="w-full flex items-center gap-3 p-4 bg-white border border-gray-200 rounded-xl hover:border-amber-300 hover:shadow-sm transition text-left"><span className="text-2xl">{type.icon}</span><div className="flex-1"><p className="text-sm font-bold text-gray-800">{type.title}</p><p className="text-xs text-gray-500">{type.desc}</p><p className="text-xs text-gray-400 mt-0.5">{type.detail}</p></div><div className="text-right"><p className="text-sm font-bold text-amber-600">{type.priceLabel}</p>{'priceSub' in type && <p className="text-xs text-gray-400">{type.priceSub}</p>}</div></button>))}
          <p className="text-xs text-gray-500 font-bold mt-2">💼 1:1 상담</p>
          {CONSULT_TYPES.filter(t => t.category === 'consultation').map(type => (<button key={type.id} onClick={() => handleConsultSelectType(type)} className={`w-full flex items-center gap-3 p-4 bg-white border rounded-xl hover:shadow-sm transition text-left ${'premium' in type ? 'border-amber-300 bg-amber-50/30' : 'border-gray-200 hover:border-amber-300'}`}><span className="text-2xl">{type.icon}</span><div className="flex-1"><p className="text-sm font-bold text-gray-800">{type.title}</p><p className="text-xs text-gray-500">{type.desc}</p><p className="text-xs text-gray-400 mt-0.5">{type.detail}</p></div><div className="text-right"><p className="text-sm font-bold text-amber-600">{type.priceLabel}</p><p className="text-xs text-gray-400">{type.sessions}회</p></div></button>))}
          {consultBookings.length > 0 && (<div className="mt-4 pt-3 border-t border-gray-200"><p className="text-xs text-gray-500 font-bold mb-2">📋 신청 내역</p>{consultBookings.map(b => (<div key={b.id} className="text-xs text-gray-600 bg-gray-50 rounded-lg p-2 mb-1">{b.type.title} {b.month ? `· ${CONSULT_YEAR}년 ${b.month}월` : ''}</div>))}</div>)}
        </div>)}
        {consultView === 'schedule' && consultScheduleData && (<div className="p-4"><button onClick={handleConsultGoBack} className="text-sm text-gray-500 mb-3">← 뒤로</button><h3 className="text-sm font-bold text-gray-800 mb-3">📅 {consultSelectedType?.title} 일정 ({CONSULT_YEAR})</h3>
          <div className="space-y-2">{consultAvailableMonths.map(m => { const isPast = isConsultMonthPast(m); const isSelected = consultSelectedMonth === m; const dates = consultScheduleData.months[m]; return (<div key={m}><button onClick={() => handleConsultSelectMonth(m)} className={`w-full flex items-center justify-between p-3 rounded-xl border-2 transition ${isPast ? 'border-gray-100 bg-gray-50 opacity-50' : isSelected ? 'border-amber-400 bg-amber-50' : 'border-gray-200 hover:border-amber-300'}`} disabled={isPast}><span className={`text-sm font-bold ${isPast ? 'text-gray-400' : 'text-gray-800'}`}>{m}월</span><span className="text-xs text-gray-500">{dates.length}회</span></button>{isSelected && (<div className="mt-1 ml-4 space-y-1">{dates.map(d => (<div key={d} className="text-xs text-gray-600 py-1">📌 {m}/{d} ({getConsultDow(CONSULT_YEAR, m, d)})</div>))}<button onClick={() => { setConsultView('confirm'); }} className="mt-2 w-full py-2.5 bg-amber-500 text-white text-sm font-bold rounded-lg">이 일정으로 신청</button></div>)}</div>); })}</div>
        </div>)}
        {consultView === 'confirm' && consultSelectedType && (<div className="p-4"><button onClick={handleConsultGoBack} className="text-sm text-gray-500 mb-3">← 뒤로</button><div className="bg-amber-50 border border-amber-200 rounded-xl p-4 mb-4"><p className="text-sm font-bold text-amber-800">{consultSelectedType.icon} {consultSelectedType.title}</p>{consultSelectedMonth && <p className="text-xs text-amber-600">{CONSULT_YEAR}년 {consultSelectedMonth}월</p>}<p className="text-2xl font-extrabold text-amber-700 mt-2">₩{consultSelectedType.price.toLocaleString()}</p></div><button onClick={handleConsultPayment} className="w-full py-3 bg-amber-500 text-white font-bold rounded-xl hover:bg-amber-600 transition">💳 결제하기 (페이플)</button><p className="text-xs text-gray-400 text-center mt-2">안전한 결제를 위해 페이플 결제 페이지로 이동합니다</p></div>)}
        {consultToast && (<div className="fixed bottom-20 left-1/2 -translate-x-1/2 bg-gray-800 text-white text-sm px-4 py-2 rounded-full shadow-lg z-[60] animate-bounce">{consultToast}</div>)}
      </div></div>)}

      {/* ═══ PIN 설정 화면 ═══ */}
      {showPinSetup && userId && (
        <PinSetupScreen
          mode={pinMode}
          userId={userId}
          onClose={() => setShowPinSetup(false)}
          onComplete={(enabled: boolean) => {
            setPinEnabledState(enabled);
            setShowPinSetup(false);
          }}
        />
      )}

    </div>
  );
}
